version: '3'

env:
  COMPOSE_FILE: docker-compose.yml
  MLFLOW_TRACKING_URI: http://mlflow:5000

tasks:
  build:
    desc: "🛠️ Build des images Docker"
    cmds:
      - docker compose -f $COMPOSE_FILE build

  up:
    desc: "🚀 Lancer tous les services (API, MLflow, Prometheus, Grafana)"
    cmds:
      - docker compose -f $COMPOSE_FILE up -d

  down:
    desc: "🛑 Arrêter tous les services"
    cmds:
      - docker compose -f $COMPOSE_FILE down

  restart:
    desc: "♻️ Redémarrer tous les services"
    cmds:
      - task down
      - task up

  logs:
    desc: "📄 Voir les logs de tous les services"
    cmds:
      - docker compose -f $COMPOSE_FILE logs -f --tail=50

  api:
    desc: "🔁 Redémarrer uniquement l’API"
    cmds:
      - docker compose -f $COMPOSE_FILE restart api

  mlflow:
    desc: "📊 Lancer seulement le serveur MLflow"
    cmds:
      - docker compose -f $COMPOSE_FILE up -d mlflow

  grafana:
    desc: "📈 Lancer seulement Grafana"
    cmds:
      - docker compose -f $COMPOSE_FILE up -d grafana

  prometheus:
    desc: "🔍 Lancer seulement Prometheus"
    cmds:
      - docker compose -f $COMPOSE_FILE up -d prometheus

  clean:
    desc: "🧹 Supprimer tous les containers et volumes"
    cmds:
      - docker compose -f $COMPOSE_FILE down -v --remove-orphans

  clean-all:
    desc: "🧨 Supprimer tous les conteneurs, volumes et images non utilisées"
    cmds:
      - docker compose -f $COMPOSE_FILE down -v --remove-orphans
      - docker image prune -f

  status:
    desc: "📌 Voir l’état de tous les containers"
    cmds:
      - docker compose -f $COMPOSE_FILE ps

  shell-api:
    desc: "💻 Ouvrir un shell dans le conteneur API"
    cmds:
      - docker compose -f $COMPOSE_FILE exec api sh

  show-env:
    desc: "🔍 Afficher les variables d’environnement courantes"
    cmds:
      - printenv | grep -E 'MLFLOW|ENV_MODE|API'

  test:
    desc: "🧪 Lancer les tests (Docker)"
    deps: [build]
    cmds:
      - docker compose -f $COMPOSE_FILE run --rm api pytest

  debug:
    desc: "🔍 Debug: containers + ports"
    cmds:
      - docker ps
      - docker compose -f $COMPOSE_FILE ps
      - docker compose -f $COMPOSE_FILE logs --tail=30

  reload-env:
    desc: "♻️ Recharger les fichiers .env dans les conteneurs (down + up)"
    cmds:
      - task down
      - task up
